info:
  contact:
    email: ${project.build.email}
    phone: ${project.build.cellphone}
  version: ${project.version}
  description: ${project.description}

spring:
  application:
    # 指定发布的微服务名(以后调用时,只需该名称即可访问该服务)spring.application.name 的优先级比eureka.instance.appname高
    name: ${project.module.turbine.monitor}
  boot:
    admin:
      username: ${config.spring.boot.admin.username}
      password: ${config.spring.boot.admin.password}
      auto-deregistration: true
      client:
        # Use the ip-address rather then the hostname in the guessed urls.
        prefer-ip: true

server:
  port: 8764
  compression:
    enabled: ${config.server.compression.enabled}

eureka:
  instance:
    appname: ${project.module.turbine.monitor}
    # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-renewal-interval-in-seconds: 30
    # 发呆时间，即服务续约到期时间（缺省为90s）
    lease-expiration-duration-in-seconds: 90
    # Eureka服务注册列表默认是显示主机名+端口,要想更方便地知道是哪台主机就需要查看ip+端口(不指定ip时自动获取)
    prefer-ip-address: true
  client:
    # 开启健康检查（需要spring-boot-starter-actuator依赖）
    healthcheck:
      enabled: ${config.eureka.client.healthcheck.enabled}
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      # 指定服务注册中心的地址(因为服务部署于一个服务器上)
      defaultZone: http://${service.discovery.node1}:${service.discovery.port}/eureka/,http://${service.discovery.node2}:${service.discovery.port}/eureka/
turbine:
  # 配置Eureka中的serviceId列表，表明监控哪些服务
  app-config: ${project.module.calculator.customer}
  aggregator:
    # 指定聚合哪些集群，多个使用","分割，默认为default。可使用http://.../turbine.stream?cluster={clusterConfig之一}访问
    cluster-config: ${config.turbine.aggregator.cluster-config}
  cluster-name-expression: new String("default")

management:
  security:
    enabled: ${config.management.security.enabled}