info:
  contact:
    email: ${project.build.email}
    phone: ${project.build.cellphone}
  version: ${project.version}
  description: ${project.description}

spring:
  application:
    # 指定发布的微服务名（以后调用时，只需该名称即可访问该服务）
    name: ${project.module.calculator.service}
  boot:
    admin:
      username: ${config.spring.boot.admin.username}
      password: ${config.spring.boot.admin.password}
      auto-deregistration: true
      client:
        # Use the ip-address rather then the hostname in the guessed urls.
        prefer-ip: true

server:
  port: 8762
  compression:
    enabled: ${config.server.compression.enabled}

eureka:
  instance:
    appname: ${project.module.calculator.service}
    # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-renewal-interval-in-seconds: 30
    # 发呆时间，即服务续约到期时间（缺省为90s）
    lease-expiration-duration-in-seconds: 90
    prefer-ip-address: true
  client:
    # 开启健康检查（需要spring-boot-starter-actuator依赖）
    healthcheck:
      enabled: ${config.eureka.client.healthcheck.enabled}
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      # 指定服务注册中心的地址(因为服务部署于一个服务器上)
      defaultZone: http://${service.discovery.node1}:${service.discovery.port}/eureka/,http://${service.discovery.node2}:${service.discovery.port}/eureka/

management:
  security:
    enabled: ${config.management.security.enabled}